//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adre
    {
        public Adre()
        {
            this.Firmas = new HashSet<Firma>();
            this.Kliencis = new HashSet<Klienci>();
        }
    
        public int id_adresu { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public Nullable<int> numer_domu { get; set; }
        public string wojewodztwo { get; set; }
        public string powiat { get; set; }
        public string gmina { get; set; }
        public string kod_pocztowy { get; set; }
    
        public virtual ICollection<Firma> Firmas { get; set; }
        public virtual ICollection<Klienci> Kliencis { get; set; }
    }
}
