//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firma
    {
        public Firma()
        {
            this.Zamowienies = new HashSet<Zamowienie>();
        }
    
        public int id_firmy { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> id_adresu { get; set; }
        public string nip { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
    
        public virtual Adre Adre { get; set; }
        public virtual ICollection<Zamowienie> Zamowienies { get; set; }
    }
}
