//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        public Towar()
        {
            this.ZamowioneTowaries = new HashSet<ZamowioneTowary>();
        }
    
        public int id_towaru { get; set; }
        public string nazwa { get; set; }
        public decimal cena { get; set; }
        public string opis { get; set; }
        public Nullable<int> id_firmy { get; set; }
    
        public virtual ICollection<ZamowioneTowary> ZamowioneTowaries { get; set; }
    }
}
