//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        public Zamowienie()
        {
            this.ZamowioneTowaries = new HashSet<ZamowioneTowary>();
        }
    
        public int id_zamowienia { get; set; }
        public int id_klienta { get; set; }
        public int id_firmy { get; set; }
        public int id_statusu { get; set; }
        public System.DateTime data_zamowienia { get; set; }
        public System.DateTime data_otrzymania { get; set; }
        public Nullable<decimal> kwota_zamowienia { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual Klienci Klienci { get; set; }
        public virtual StatusZamowienia StatusZamowienia { get; set; }
        public virtual ICollection<ZamowioneTowary> ZamowioneTowaries { get; set; }
    }
}
