//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace systemOrders
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowioneTowary
    {
        public int id_zamowione_tow { get; set; }
        public int id_zamowienia { get; set; }
        public int id_towaru { get; set; }
        public int ilosc { get; set; }
        public decimal kwota { get; set; }
    
        public virtual Towar Towar { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
